FROM openjdk:11

ARG PROFILE
ARG ADDITIONAL_OPTS

ENV PROFILE=${PROFILE}
ENV ADDITIONAL_OPTS={ADDITIONAL_OPTS}

WORKDIR /opt

COPY /target/Java2-0.0.1-SNAPSHOT.jar /opt/Java2.jar

SHELL ["/bin/sh","-c"]

EXPOSE 55005
EXPOSE 8080

CMD java ${ADDITIONAL_OPTS} -jar Java2-0.0.1-SNAPSHOT.jar --spring.profiles.active={PROFILE}